<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="51878" started-at="2018-06-22T05:41:26Z" finished-at="2018-06-22T05:42:18Z">
    <groups>
    </groups>
    <test name="Test" duration-ms="51878" started-at="2018-06-22T05:41:26Z" finished-at="2018-06-22T05:42:18Z">
      <class name="com.TestCases.Tc_01_ValidateLogin">
        <test-method status="FAIL" signature="Tc_01_ValidateLoginCredentials()[pri:0, instance:com.TestCases.Tc_01_ValidateLogin@1fc5af1]" name="Tc_01_ValidateLoginCredentials" duration-ms="48494" started-at="2018-06-22T11:11:29Z" finished-at="2018-06-22T11:12:18Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerExceptionat com.codoid.products.fillo.SelectExcelUtil.runSelectQuery(SelectExcelUtil.java:46)at com.codoid.products.fillo.Select.getRecordset(Select.java:61)at com.codoid.products.fillo.Connection.executeQuery(Connection.java:56)at com.GenericFunctions.GenericFunctions.senddata(GenericFunctions.java:368)at com.TestCases.Tc_01_ValidateLogin.Tc_01_ValidateLoginCredentials(Tc_01_ValidateLogin.java:35)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)at java.lang.reflect.Method.invoke(Method.java:498)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- Tc_01_ValidateLoginCredentials -->
      </class> <!-- com.TestCases.Tc_01_ValidateLogin -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
